### ISSUE TITLE
Please add favorite note screen

### ISSUE THREAD

**Issue by aminsamad** [ishworpanta10/flutter_notes_with_sqflite#1]

**Comment by ishworpanta10** [comment]
Ok I will do it today. If you like my project do star.

**Comment by ishworpanta10** [comment]
completed addding favorite. please unstall and reinstall app.

**Comment by ishworpanta10** [comment]
completed adding fav screen .please unistall and reinstall app

**Comment by ishworpanta10** [comment]
there was some problem in loading note page now issue is fixed please pull
latest commit
