### ISSUE TITLE
How to add favorite button in detail screen

### ISSUE THREAD

**Issue by aminsamad** [ishworpanta10/flutter_notes_with_sqflite#2]
Brother thanks for adding favorite screen but how to add favorite button in detail screen without switch and without edit note like this video 

![favorite](https://user-images.githubusercontent.com/73881942/130067533-48b12143-23d4-4cb7-8a67-1fe478c495eb.gif)

Thanks.

**Comment by ishworpanta10** [comment]
Are u looking like this
https://play.google.com/store/apps/details?id=com.ishworpanta.quotes_and_status_offline
 install and review I will add that soon

**Comment by ishworpanta10** [comment]
will add soon

**Comment by ishworpanta10** [comment]
will adding soon
